language: node_js
sudo: false

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

env:
  - CODECLIMATE_REPO_TOKEN=c661e2fffd4e60b952d1b7029c9435f7f8e52f6c8106bf8dff7b1bf65ecacb00

after_success:
  - npm run-script coverage
  - npm run-script codeclimate

